# -*- coding: utf-8 -*-
"""final_recommender

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/vedshivhare/final-recommender.b510ccf0-299e-4832-a2c9-33b0f62c6a6d.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260307/auto/storage/goog4_request%26X-Goog-Date%3D20260307T190152Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D14c19da9f39050a52577f40324b40dd33a96bd2e32bc58064232be12d79b806d7218fe098a8c47a2fab4daf1940dda22e0b05c0cb827e5fa66787a970fbd7b662118b7b72581097cd28070658a6f28e519c309b77eff00898ec24aad8716bcf29c31669fb7c898275fef161e7aaaa187d1c613c9618ddb95a4e5277bc8bdf1163e9fe634ee2f4b7882eeeb71aa01103b000c14871aca534a381ac3cfea67039ba6acc175007ccba03b123168186ef120eff771031b95ff3b583b655857a9578ef88ab0140c07e7ccfcaff63e6f90a1bcfec23db7b5acb8fd98eb8feda9e00b719fbfd73c5a3716db80f1bd3969a901430d2b2e19c234211967eedee076a93a46
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

vedshivhare_cleaned_path = kagglehub.dataset_download('vedshivhare/cleaned')
vedshivhare_final_cleaned_path = kagglehub.dataset_download('vedshivhare/final-cleaned')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

!pip install faiss-cpu

df = pd.read_csv("/kaggle/input/datasets/vedshivhare/final-cleaned/final_cleaned_courses.csv")

df.info()

df.isnull().sum()

df["combined_text"] = df["combined_text"].fillna("")

df = df[df["combined_text"].str.strip() != ""]

df["combined_text"] = df["combined_text"].str[:512]

course_text = df["combined_text"].tolist()

import faiss
import pickle

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

course_embeddings = model.encode(
    course_text,
    batch_size=256,
    show_progress_bar=True,
    convert_to_numpy=True
)

course_embeddings = course_embeddings.astype("float32")

print(course_embeddings.shape)

faiss.normalize_L2(course_embeddings)

dimension = course_embeddings.shape[1]

index = faiss.IndexFlatIP(dimension)

index.add(course_embeddings)

print("Total vectors in FAISS:", index.ntotal)

course_to_idx = pd.Series(
    df.index,
    index=df["Course_Name"]
).drop_duplicates()

import numpy as np

def apply_hybrid_ranking(scores, indices, top_k=10):

    candidates = df.iloc[indices[0]].copy()

    candidates["similarity"] = scores[0]

    candidates["rating_score"] = candidates["Rating"] / 5

    candidates["popularity_score"] = np.log1p(candidates["Reviews"])

    candidates["final_score"] = (
        0.7 * candidates["similarity"]
        + 0.2 * candidates["rating_score"]
        + 0.1 * candidates["popularity_score"]
    )

    candidates = candidates.sort_values("final_score", ascending=False)

    return candidates.head(top_k)[[
        "Course_Name",
        "Rating",
        "Reviews",
        "Platform",
        "Level",
        "Course_Url"
    ]]

def recommend_by_query(query, top_k=10):

    query_embedding = model.encode([query]).astype("float32")

    faiss.normalize_L2(query_embedding)

    scores, indices = index.search(query_embedding, 50)

    return apply_hybrid_ranking(scores, indices, top_k)

def recommend_courses(course_name, top_k=10):

    if course_name not in course_to_idx:
        return "Course not found"

    idx = course_to_idx[course_name]

    query_vector = course_embeddings[idx].reshape(1, -1)

    scores, indices = index.search(query_vector, 50)

    return apply_hybrid_ranking(scores, indices, top_k)

from difflib import get_close_matches

def recommend(input_text, top_k=10):
    match = get_close_matches(input_text, df["Course_Name"], n=1, cutoff=0.8)

    # If input is a known course
    if match:
        return recommend_courses(match[0])
    else:
        return recommend_by_query(input_text)

recommend("R Programming for Data Science")

recommend("Data Science")