# -*- coding: utf-8 -*-
"""final_data_cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/vedshivhare/final-data-cleaning.a9374341-dd47-463b-b8a9-86a8a2dcde2e.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260307/auto/storage/goog4_request%26X-Goog-Date%3D20260307T185624Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D120c9f8e46c869a2dd8f18c9fdcd534ea77c7ac46721a207623e59f03ab82ae583f9550aed0df8d49856800a0771e54c0dfc81a8bb888d84b80c6f9ed09b4a99de4515bb421b0a38d28a51b8a44027b4955104c6c1c934eccf23cd5fcae385cec01f504740a04c0b1ec7b04fd5e3b0aaaa36f3e0e3cd419f1b0de0b4fc94d3386b4c030a52a01bc1488d23683332963ee5f97491c04c2990239fa3bec8bff024ae560c802deca24d23a972da8491cf9b8a1029fa0458f9869f76505011846ce076d035e0298e424ebbb637b93f0626a3475f75b30d46e982fae2c912433458389d868fdd07e057796e65a0f00c6a8378eb38dd5ab1a3b42668a69db4a3e1f594
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

vedshivhare_udemy_and_coursera_with_url_path = kagglehub.dataset_download('vedshivhare/udemy-and-coursera-with-url')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

udemy_path = "/kaggle/input/datasets/vedshivhare/udemy-and-coursera-with-url/udemy_courses.csv"
coursera_path = "/kaggle/input/datasets/vedshivhare/udemy-and-coursera-with-url/coursera_course_2024.csv"

udemy_df = pd.read_csv(udemy_path)
coursera_df = pd.read_csv(coursera_path)

print("Udemy Dataset Shape:", udemy_df.shape)
print("Coursera Dataset Shape:", coursera_df.shape)

print(udemy_df.columns)

print(coursera_df.columns)

udemy_df.drop(columns=['id','num_published_lectures','created', 'last_update_date','instructors_id'], inplace=True, errors='ignore')
coursera_df.drop(columns=['Unnamed: 0','enrolled', 'Instructor', 'Organization','Modules/Courses','Satisfaction Rate'], inplace=True, errors='ignore')

coursera_df.columns

udemy_df.columns

udemy_df.rename(columns={
    'title':'Course_Name',
    'num_reviews':'Reviews',
    'rating':'Rating',
    'duration':'Duration',
    'url':'Course_Url',
    'image': 'Image'
}, inplace=True)

udemy_df['Platform'] = 'Udemy'
udemy_df['Skills'] = None
udemy_df['Description'] = None
udemy_df['Level'] = None

coursera_df.rename(columns={
    'title':'Course_Name',
    'num_reviews':'Reviews',
    'rating':'Rating',
    'Schedule':'Duration',
    'URL':'Course_Url',
}, inplace=True)

coursera_df['Platform'] = 'Coursera'
coursera_df['Image'] = None

df_courses = pd.concat([udemy_df, coursera_df], ignore_index=True)

df_courses.head()

df_courses.drop_duplicates(subset="Course_Name", inplace=True)

df_courses.shape

df_courses.isnull().sum()

df_courses["Reviews"] = df_courses["Reviews"].fillna(0)
df_courses["Duration"] = df_courses["Duration"].fillna("Unknown")
df_courses["Duration"] = df_courses["Duration"].fillna("Unknown")
df_courses["Skills"] = df_courses["Skills"].fillna("")
df_courses["Description"] = df_courses["Description"].fillna("")
df_courses["Level"] = df_courses["Level"].fillna("Not Specified")
df_courses["Image"] = df_courses["Image"].fillna("No_Image")

df_courses.head()

df_courses["combined_text"] = (
    df_courses["Course_Name"] + " " +
    df_courses["Description"] + " " +
    df_courses["Skills"]
)

df_courses.drop(["Skills","Description"],axis=1,inplace=True)

df_courses.head()

import re
import numpy as np

def clean_duration(x):

    if pd.isna(x):
        return np.nan

    x = str(x).lower()

    # case 1: total hours
    match = re.search(r'(\d+\.?\d*)\s*total hours', x)
    if match:
        return float(match.group(1))

    # case 2: total mins
    match = re.search(r'(\d+\.?\d*)\s*total mins', x)
    if match:
        return float(match.group(1)) / 60

    # case 3: hours to complete
    match = re.search(r'(\d+\.?\d*)\s*hours to complete', x)
    if match:
        return float(match.group(1))

    # case 4: questions → not duration
    if "questions" in x:
        return np.nan

    return np.nan


df_courses["Duration_hours"] = df_courses["Duration"].apply(clean_duration)

df_courses["Duration_hours"].isnull().sum()

df_courses.drop(["Duration"] , axis=1 , inplace = True)

def duration_category(x):
    if pd.isna(x):
        return "Unknown"
    elif x < 3:
        return "Short"
    elif x < 15:
        return "Medium"
    else:
        return "Long"

df_courses["Duration_Category"] = df_courses["Duration_hours"].apply(duration_category)

df_courses.head()

df_courses["Duration_Category"].value_counts()

df_courses["Course_Url"] = df_courses.apply(
    lambda row: "https://www.udemy.com" + row["Course_Url"]
    if row["Platform"] == "Udemy" and row["Course_Url"].startswith("/")
    else row["Course_Url"],
    axis=1
)

df_courses["Course_Url"] = df_courses["Course_Url"].str.rstrip("/")

df_courses[df_courses["Platform"] == "Udemy"]["Course_Url"].head(10)

df_courses[df_courses["Platform"] == "Coursera"]["Course_Url"].head(10)

import re

# Clean combined_text column
df_courses["combined_text"] = (
    df_courses["combined_text"]
    .str.lower()                                   # lowercase
    .str.replace(r"http\S+|www\S+", "", regex=True) # remove urls
    .str.replace(r"\d+", "", regex=True)            # remove numbers
    .str.replace(r"[^a-z\s]", " ", regex=True)      # remove punctuation
    .str.replace(r"\b[a-z]{1,2}\b", "", regex=True) # remove very short words
    .str.replace(r"\s+", " ", regex=True)           # remove extra spaces
    .str.strip()                                    # trim spaces
)

df_courses.head()

df_courses.isnull().sum()

df_courses.to_csv("/kaggle/working/cleaned_courses_dataset.csv", index=False)